### ISSUE TITLE
Error in MATLAB

### ISSUE THREAD

**Issue by Sina-Tabeiy** [modenaxe/msk-bone-deformation#7]
Dear Modenaxe,
I've been trying to open your model in MATLAB but whenever I tried MATLAB showed this error:

Undefined variable "GC5" or class "GC5.osim".

Error in create_femAnt_models (line 57)
    osimModel = Model(GC5.osim);"
    
How can I fix this?

Ps: This error showed up while the code "create-femAnt-model.m" was being run.

**Comment by modenaxe** [comment]
Hi Sina, 
I assume you are referring to the repository that replicates the manuscript results.
Line 57 reads:
> osimModel = Model(modelFileName);
This should work, are you sure you have the OpenSim MATLAB API properly installed?
Luca

**Comment by modenaxe** [comment]
@Sina-Tabeiy is this solved?

**Comment by Sina-Tabeiy** [comment]
Dear Luca,

Thank you so much for your kindness; Also, my apologies for the late reply.
I re-installed Oensim API and unfortunately, another error showed up:

Error using create_femAnt_models (line 57)
Java exception occurred:
java.io.IOException: Object: Cannot open file modelFileName. It may not exist or you do not have permission to read it.
	Thrown at Object.cpp:105 in Object().

	at org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_1(Native Method)

	at org.opensim.modeling.Model.<init>(Model.java:783)

BTW I installed OpenSim API for OpenSim 4.2, does it make any problem while running the script? (last time I tried to run your script my OpenSim API version was 3.3)

Best regards,

Sina

**Comment by modenaxe** [comment]
Hi Sina,
The error you are reporting is not from the bone deformation toolbox but from the OpenSim API. You need to ensure that the model that you are trying to open is on the path specified as input of the Model() method, otherwise you will keep getting the error. Are you working with the material from this repository or the paper one? In the second case please post your issue on that repository.
Cheers,
Luca

**Comment by Sina-Tabeiy** [comment]
Hi luca,
Thank you for your nice guidance. Having tried different ways finally paid off! BTW I faced some other issues which I'm gonna post on your paper repository.
Sincerely,
Sina
